### ISSUE TITLE
Failed to load qb-houserobbery

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-houserobbery#17]
![aaaaa](https://user-images.githubusercontent.com/71113131/141363931-418484da-9133-45d0-8599-2d4128d82178.png)

**Comment by jnccloud** [comment]
You are missing the `fxmanifest.lua` file or it's corrupted. This isn't really a bug. The Discord can help with these types of issues better than Github can.

**Comment by OxGhali** [comment]
no there is fxmanifest.lua and the script is the same i didn't change anything
