### ISSUE TITLE
No idea on how to get it to work

### ISSUE THREAD

**Issue by PlzAdoptMee** [qbcore-framework/qb-houserobbery#23]
I make the advance lockpick and I go around every house in downtown to use it but it will not work anywhere

**Comment by yamieboi** [comment]
> I make the advance lockpick and I go around every house in downtown to use it but it will not work anywhere


Alright So, i tried it by downloading  the latest one from github and it worked with the advanced lockpick...Did you have enough cops or maybe just try setting it to 0 in the config?

**Comment by PlzAdoptMee** [comment]
Yes, I did set the police configuration to 0 and it still doesn't work. I'm not sure why I can't rob a house.  Do I need a gun on my character?

**Comment by yamieboi** [comment]
no shouldnt need a gun. are you at the correct house tho?

**Comment by PlzAdoptMee** [comment]
The houses in the downtown area where the gang is. I tried about all those and the houses in mirror park.

**Comment by yamieboi** [comment]
did u try one from config?

**Comment by yamieboi** [comment]
please get support from discord...
