### ISSUE TITLE
[BUG] Not Unlocking When Changing minigame 

### ISSUE THREAD

**Issue by KaS3Coder** [qbcore-framework/qb-houserobbery#43]
I changed the export for the mini game and now the doors wont "unlock" the mini game works but i get nothing for the door to go into the house
![bug1](https://user-images.githubusercontent.com/46138616/178031097-e0f897f9-7619-44bb-a9f6-2fabf843ca3a.png)
![cantgoin](https://user-images.githubusercontent.com/46138616/178031154-ef3421b7-66b2-45ac-855d-cd8b0c3cbe56.png)

**Comment by Jamesmayl** [comment]
Can you send the code that you chagned? @KaS3Coder
