### ISSUE TITLE
[BUG] House does not lock after the exiting

### ISSUE THREAD

**Issue by Retired1SGDW** [qbcore-framework/qb-houserobbery#44]
I wanted to see if there is a function to lock the door after the person leaves the house after leaving it. When a person lockpicks the house they actually can leave and come back after the police leave the area and reenter the house. Is there something that can be fixed with this functionality. 

Also when a person goes up to the door it asks for an advanced lockpick and screwdriver set but it only requires an advanced lockpick, is there any fixes for this functionality to require a lockpick and screwdriver set or an advanced lockpick.

**Comment by spicebag** [comment]
Hi there,
The doors actually do lock after a bit of time, does it not do that for you?

Thanks
- QBDev

**Comment by Retired1SGDW** [comment]
It does lock when the time comes up for the house robberies to end but generally as long as someone is around the house it does not reset which criminals are opening the door going outside waiting for the cops to leave and then reentering. We have warned people but you know how players are sometimes. I was just wondering if there is another alternative to the door locking.

**Comment by rodrigoandrade1** [comment]
After a certain time the door locks and the house resets all the robbery points, after that anyone who wants to enter the house will have to use a lockpick again and it will be a new robbery, starting a new count.
