### ISSUE TITLE
[SUGGESTION] Add mini-game for house alarm (cop ping)

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-houserobbery#50]
**Is your feature request related to a problem? Please describe.**
Basically the cops get to house robberies too fast, so the only way to combat that is to lower the chance of a ping by heaps.

**Describe the feature you'd like**
On entering the house, the robber will have the option to 3rd eye the door and choose "disable alarm" and a minigame pops up where they need to match coloured wires before a timer runs out to disable the alarm. If successful the police are not triggered, if they fail it or make a mistake, the cops are pinged and an alarm sound is played (adds to the pressure of completing the job). Up to the player if they continue to gap out of the house.

If the player doesn't use the 3rd eye option, then I guess you could have two configs for it:
1, Always ping police if minigame is not used
2. % chance to ping police if minigame is not used

**Describe alternatives you've considered**
Self-coding it and making a PR. I might still do this if I can find someone interested in doing it.

**Additional context**
Minigame like this would be awesome:
https://i.ytimg.com/vi/_ieT1mlNAqk/maxresdefault.jpg

**Comment by spicebag** [comment]
Hi there, from what I've been told this is already possible by using hacking. 
Thanks

- QBCore Developer Kira

**Comment by nzkfc** [comment]
As far as I'm aware it's not built in already with a config etc,  which is
what a suggestion/enhancement is all about.

Not everyone running qb-core is a full lua dev.

**Comment by spicebag** [comment]
Which is completely fine, but not everyone may want this introduced into QBCore, but if it is to be added maybe it could be the same hack that qb-bankrobbery has?

We'd need to make HTML and such for it to be introduced natively, but I'll look into it.

- QBCore Developer Kira

**Comment by nzkfc** [comment]
And that's why it's a config,  you make one for if it's used or not
(true/false) and then one for whatever settings are deemed needed for it
e.g. Time to hack it,  difficulty etc.

Obviously if you used hacking game from standalone it would then be a
dependancy which I know Kakarot wants to avoid,  but then writing a new one
built into houses makes it more work etc so I understand. Would just boost
the scripts use more,  right now people don't Rob many houses as it pings
cops pretty much instantly.

**Comment by spicebag** [comment]
I'll look into it, but in the meantime I'd recommend just having a server rule that doesn't allow constant robberies.

Thanks
- QBCore Developer Kira

**Comment by spicebag** [comment]
Welp, I don't develop for QBCore anymore so I ain't gonna be doing this, just know that it **was** being worked on by me until Kakarot removed me unfairly from the team without reason.

The developer's for QBCore don't get anything for doing hours of work, nor do they get actual help unless you find someone who's in a good mood. Good luck.
