### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by elkie1991gaming** [qbcore-framework/qb-houserobbery#55]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to any of the robbery locations in the house
2. Click E to start robbing and start the mini game
3. you can repeatedly do the mini game and it will keep giving you items and will not stop till you finish 
4.No errors given

**Expected behavior**

**Screenshots**
[https://i.imgur.com/BdSiEYi.png]
[https://i.imgur.com/YSnEm5l.png]
[https://i.imgur.com/Y0UvRjF.png]
[https://i.imgur.com/cKDF4kn.png]

**Questions (please complete the following information):**
 - When you last updated: last week fresh recipe
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by Molicheu** [comment]
This is true, I have the same issue

**Comment by JordanBScott** [comment]
Same here. Looking for a fix soon

**Comment by rafaelval** [comment]
> **Describe the bug** A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to any of the robbery locations in the house
> 2. Click E to start robbing and start the mini game
> 3. you can repeatedly do the mini game and it will keep giving you items and will not stop till you finish
>    4.No errors given
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. [https://i.imgur.com/BdSiEYi.png] [https://i.imgur.com/YSnEm5l.png] [https://i.imgur.com/Y0UvRjF.png] [https://i.imgur.com/cKDF4kn.png]
> 
> **Questions (please complete the following information):**
> 
> * When you last updated: last week fresh recipe
> * Are you using custom resource? which ones? qb-target
> * Have you renamed `qb-` to something custom? no
> 
> **Additional context** Add any other context about the problem here.

![image](https://user-images.githubusercontent.com/84647580/196313683-d8098de6-c87b-4abe-b64a-e29309d41443.png)
just comment or del that line on client/main.lua

**Comment by rafaelval** [comment]
![image](https://user-images.githubusercontent.com/84647580/196314199-7197ee83-fb16-4fcb-8446-96cbec3b344d.png)
here it is: on client/main.lua, change the line that says 'SucceededAttempts = 0' on 168 , put it three lines below as in the picture, sorry if my eglish is bad

**Comment by tom-osborne** [comment]
This was fixed in https://github.com/qbcore-framework/qb-skillbar/pull/13

Please update your qb-skillbar resource.
